update

diff --git a/bin/backup-zfs b/bin/backup-zfs
--- a/bin/backup-zfs
+++ b/bin/backup-zfs
@@ -173,15 +173,25 @@ last="$(
 ###
 # 1st time: send full snapshot
 if [[ -z $last ]] ; then
-	log "sending full recursive snapshot from $src to $dest"
-	ZFS "$srchost" send "$send_opts" --raw -R "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs full send failed ☠️"
+	log "FULL SEND: $cur"
+
+	# clean target if snapshots are missing
+	if ZFS "$desthost" list -H -o name "$destfs/$srcbase" &>/dev/null ; then
+		log "cleaning up old snapshots on $destfs/$srcbase before full send"
+		ZFS "$desthost" destroy -r "$destfs/$srcbase" || die $? "failed to destroy old snapshots on $destfs/$srcbase"
+	fi
+
+	ZFS "$srchost" send "$send_opts" --raw -R "$cur" | ZFS "$desthost" receive "$recv_opts" -F -u -e "$destfs" || die $? "zfs full send failed ☠️"
+
 # special case: tagged snapshots exist on dest, but src has rotated through all
-elif ! ZFS "$srchost" list "$srcfs"@"$last" &>/dev/null ; then
-	die 1 "no incremental path from from $src to $dest"
+elif ! ZFS "$srchost" list "$srcfs@$last" &>/dev/null ; then
+	die 1 "no incremental path from $src to $dest ☠️"
+
 # normal case: send incremental
 else
 	log "sending incremental snapshot from $src to $dest (${last#"${tag}"_}..${cur#*@"${tag}"_})"
-	ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs incremental send failed"
+	ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" | \
+		ZFS "$desthost" receive "$recv_opts" -F -u -e "$destfs" || die $? "zfs incremental send failed"
 fi
 
 ###
