Update sending ZFS Snapshots

diff --git a/bin/backup-zfs b/bin/backup-zfs
--- a/bin/backup-zfs
+++ b/bin/backup-zfs
@@ -71,6 +71,8 @@ quiet=false
 tossh=false
 fromssh=false
 port=22
+send_opts=""
+recv_opts=""
 
 ###
 ### parse options
@@ -163,13 +165,13 @@ if $tossh ; then
 	else
 		log "sending $([[ -n $gpgid ]] && echo "encrypted ")incremental snapshot from $src to $dest (${last#"${tag}"_}..${cur#*@"${tag}"_})"
 		if [[ -n $gpgid ]] ; then
-			ZFS "$srchost" send "$send_opts" --raw -R -i "$last" "$cur" \
+			ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" \
 				| gpg --trust-model always --encrypt --recipient "$gpgid" \
 				| ssh "$desthost" zfswrite "${tag}_$date.zfssnap.gpg" \
 				|| die $? "zfs incremental send failed"
 			ssh "$desthost" zfslast "$snap"
 		else
-			ZFS "$srchost" send "$send_opts" --raw -R -i "$last" "$cur" \
+			ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" \
 				| ssh "$desthost" zfswrite "${tag}_$date.zfssnap" \
 				|| die $? "zfs incremental send failed"
 			ssh "$desthost" zfslast "$snap"
@@ -229,6 +231,20 @@ if [[ $(ZFS "$desthost" list -H -o name "$destfs" 2>/dev/null) != "$destfs" ]] ;
 fi
 
 ###
+### resume token support (before creating new snapshot)
+###
+resume_token="$(
+	ZFS "$desthost" get -H -o value receive_resume_token "$destfs/$srcbase" 2>/dev/null | tr -d '[:space:]'
+)"
+
+if [[ -n "$resume_token" && "$resume_token" != "-" ]]; then
+	log "resuming interrupted zfs send/receive operation for $destfs/$srcbase"
+	ZFS "$srchost" send -t "$resume_token" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" \
+		|| die $? "resume failed"
+	exit
+fi
+
+###
 ### create new snapshot on src
 ###
 cur="$srcfs@${tag}_$date"
@@ -236,8 +252,14 @@ ZFS "$srchost" snapshot -r "$cur" || die $? "zfs snapshot failed ☠️"
 
 ###
 ### get newest snapshot on dest - it must exist on src
+### (only snapshots with fitting Tag)
 ###
-last="$(ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name "$destfs"/"$srcbase" | head -n1 | cut -f2 -d@)"
+last="$(
+	ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name "$destfs/$srcbase" 2>/dev/null \
+		| grep "@${tag}_" \
+		| head -n1 \
+		| cut -f2 -d@
+)"
 
 ###
 ### send & receive
@@ -252,14 +274,14 @@ elif ! ZFS "$srchost" list "$srcfs"@"$last" &>/dev/null ; then
 # normal case: send incremental
 else
 	log "sending incremental snapshot from $src to $dest (${last#"${tag}"_}..${cur#*@"${tag}"_})"
-	ZFS "$srchost" send "$send_opts" --raw -R -i "$last" "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs incremental send failed ☠️"
+	ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs incremental send failed"
 fi
 
 ###
 ### clean up old snapshots
 ###
 for snap in $(ZFS "$srchost" list -d 1 -t snapshot -H -S creation -o name "$srcfs" \
-	      | grep -F "@${tag}_" | cut -f2 -d@ | tail -n+$((keep+1)) ) ;
+		| grep -F "@${tag}_" | cut -f2 -d@ | tail -n+$((keep+1)) ) ;
 do
 	ZFS "$srchost" destroy -r "$srcfs"@"$snap"
 done
