update

diff --git a/bin/backup-zfs b/bin/backup-zfs
--- a/bin/backup-zfs
+++ b/bin/backup-zfs
@@ -1,8 +1,4 @@
 #!/usr/bin/env bash
-set -euo pipefail
-exec 9>/var/lock/backup-zfs.lock
-flock -n 9 || die 1 "another instance already running"
-IFS=$'\n\t'
 # backup-zfs: use zfs send/recv to push/pull snapshots
 prog="$(basename "$0")"
 
@@ -21,22 +17,6 @@ usage() {
 	  -t tag       tag to use for naming snapshots (default: backup-zfs)
 	  -k keep      number of snapshots to keep on src (default: 5)
 	  -d dateopts  options for date(1) - used to name the snapshots (default: +%F_%T)
-
-	  # Local mode: Backup tank/system to backup/tank/system
-	  backup-zfs tank/system backup/tank
-
-	  # Pull mode: Backup tank/system on tankhost to localhost
-	  backup-zfs tankhost:tank/system backup/tank
-
-	  # Push mode: Backup tank/system on localhost to backuphost
-	  backup-zfs tank/system backuphost:backup/tank
-
-	  # Double remote mode: Backup tank/system on tankhost to backuphost
-	  backup-zfs tankhost:tank/system backuphost:backup/tank
-
-	  # In this mode, your client will establish two separate SSH sessions,
-	  # connect them with a pipe, and pull data from one while pushing to the
-	  # other. No data will be stored locally.
 	EOF
 	exit "$1"
 }
@@ -44,10 +24,9 @@ usage() {
 # log to syslog; if verbose or on a tty, also to stdout
 # usage: log msg
 log() {
-	ts="$(date '+%F %T')"
 	logger -t "$prog" -- "$@"
-	if ! $quiet && { [[ -t 1 ]] || $verbose; }; then
-		echo "[$ts] $@" >&2
+	if ! $quiet && [[ -t 1 ]] || $verbose ; then
+		echo "$@" >&2
 	fi
 }
 
@@ -57,7 +36,7 @@ die() {
 	code="$1"
 	shift
 	if [[ $code -ne 0 ]] ; then
-		verbose=true log "FATAL: $*"
+		verbose=true log "FATAL: $@"
 	else
 		log "$@"
 	fi
@@ -69,19 +48,12 @@ die() {
 ZFS() {
 	host="$1"
 	shift
-
-	local cmd=(zfs "$@")
-
-	# join arguments safely with space for logging only
-	local logline
-	logline="$(printf '%s ' "${cmd[@]}")"
-
 	if [[ -n $host ]] ; then
-		log "remote ($host): ${logline% }"
- 		ssh -C -p "$port" "$host" "${cmd[@]}"
+		log "remote ($host): zfs $@"
+		ssh -C -p "$port" "$host" zfs "$@"
 	else
-		log "local: ${logline% }"
-		"${cmd[@]}"
+		log "local: zfs $@"
+		zfs "$@"
 	fi
 }
 
@@ -138,9 +110,7 @@ dest="$2"
 srcfs="${src#*:}"
 destfs="${dest#*:}"
 
-# if there is a colon, discard everything after it to get the host
-srchost=""
-desthost=""
+# iff there is a colon, discard everything after it to get the host
 [[ $src =~ : ]] && srchost="${src%:*}"
 [[ $dest =~ : ]] && desthost="${dest%:*}"
 
@@ -173,7 +143,7 @@ if [[ -n "$resume_token" && "$resume_token" != "-" ]]; then
 	fi
 
 	log "resuming interrupted zfs send/receive operation"
-	if ZFS "$srchost" send -t "$resume_token" | ZFS "$desthost" receive $recv_opts -F -u -e "$destfs" ; then
+	if ZFS "$srchost" send -t "$resume_token" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" ; then
 		log "resume completed successfully"
 		exit
 	else
@@ -204,15 +174,14 @@ last="$(
 # 1st time: send full snapshot
 if [[ -z $last ]] ; then
 	log "sending full recursive snapshot from $src to $dest"
-	ZFS "$srchost" send "$send_opts" --raw -R "$cur" | ZFS "$desthost" receive $recv_opts -F -u -e "$destfs" || die $? "zfs full send failed ☠️"
+	ZFS "$srchost" send "$send_opts" --raw -R "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs full send failed ☠️"
 # special case: tagged snapshots exist on dest, but src has rotated through all
 elif ! ZFS "$srchost" list "$srcfs"@"$last" &>/dev/null ; then
-	log "no incremental path found 💩 - falling back to full send"
-	last=""
+	die 1 "no incremental path from from $src to $dest"
 # normal case: send incremental
 else
 	log "sending incremental snapshot from $src to $dest (${last#"${tag}"_}..${cur#*@"${tag}"_})"
-	ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" | ZFS "$desthost" receive $recv_opts -F -u -e "$destfs" || die $? "zfs incremental send failed"
+	ZFS "$srchost" send "$send_opts" --raw -R -I "$last" "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs incremental send failed"
 fi
 
 ###
@@ -222,5 +191,4 @@ for snap in $(ZFS "$srchost" list -d 1 -t snapshot -H -S creation -o name "$srcf
 		| grep -F "@${tag}_" | cut -f2 -d@ | tail -n+$((keep+1)) ) ;
 do
 	ZFS "$srchost" destroy -r "$srcfs"@"$snap"
-	log "destroying old snapshot srchost : $snap"
 done
