Apply changes from shell check

diff --git a/bin/backup-zfs b/bin/backup-zfs
--- a/bin/backup-zfs
+++ b/bin/backup-zfs
@@ -21,7 +21,7 @@ usage() {
 	  -r           read mode - read snaps from ssh server to local fs
 	  -g gpg-id    gpg recipient key id (store mode only)
 	EOF
-	exit $1
+	exit "$1"
 }
 
 # log to syslog; if verbose or on a tty, also to stdout
@@ -39,11 +39,11 @@ die() {
 	code="$1"
 	shift
 	if [[ $code -ne 0 ]] ; then
-		verbose=true log "FATAL: $@"
+		verbose=true log "FATAL: $*"
 	else
 		log "$@"
 	fi
-	exit $code
+	exit "$code"
 }
 
 # run zfs(1) command either locally or via ssh
@@ -52,10 +52,10 @@ ZFS() {
 	host="$1"
 	shift
 	if [[ -n $host ]] ; then
-		log "remote ($host): zfs $@"
-		ssh -C -p $port "$host" zfs "$@"
+		log "remote ($host): zfs $*"
+		ssh -C -p "$port" "$host" zfs "$*"
 	else
-		log "local: zfs $@"
+		log "local: zfs $*"
 		zfs "$@"
 	fi
 }
@@ -95,7 +95,7 @@ while getopts "hvqk:p:t:d:srg:" opt ; do
 	esac
 done
 shift $((OPTIND-1))
-date="$(date $dateopts)"
+date="$(date "$dateopts")"
 $tossh && $fromssh && die 1 "-s and -r are mutually exclusive"
 if ! $tossh && [[ -n $gpgid ]] ; then
 	die 1 "-g can only be used with -s"
@@ -124,14 +124,13 @@ if $tossh ; then
 	# make sure src exists
 	if [[ $src =~ : ]] ; then
 		die 1 "$src must be a local zfs filesystem"
-	elif [[ $(ZFS "" list -H -o name "$src" 2>/dev/null) != $src ]] ; then
+	elif [[ $(ZFS "" list -H -o name "$src" 2>/dev/null) != "$src" ]] ; then
 		die 1 "$src must be a local zfs filesystem"
 	fi
 
 	# split dest to components
 	if [[ $dest =~ : ]] ; then
 		desthost="${dest%:*}"
-		destpath="${dest#*:}"
 	else
 		die 1 "$dest must be ssh host:path"
 	fi
@@ -149,7 +148,6 @@ if $tossh ; then
 	###
 	### get newest snapshot on dest - it must exist on src
 	###
-	#last="$(ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name $destfs/$srcbase | head -n1 | cut -f2 -d@)"
 	last="$(ssh "$desthost" zfslast)"
 
 	###
@@ -159,20 +157,19 @@ if $tossh ; then
 	if [[ -z $last ]] ; then
 		die 1 "ssh path contains no .last file"
 	# special case: tagged snapshots exist on dest, but src has rotated through all
-	elif ! ZFS "$srchost" list $src@$last &>/dev/null ; then
+	elif ! ZFS "$srchost" list "$src"@"$last" &>/dev/null ; then
 		die 1 "no incremental path from from $src to $dest"
 	# normal case: send incremental
 	else
-		log "sending $([[ -n $gpgid ]] && echo "encrypted ")incremental snapshot from $src to $dest (${last#${tag}_}..${cur#*@${tag}_})"
-		#ZFS "$srchost" send $send_opts -R -i "$last" "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs incremental send failed"
+		log "sending $([[ -n $gpgid ]] && echo "encrypted ")incremental snapshot from $src to $dest (${last#"${tag}"_}..${cur#*@"${tag}"_})"
 		if [[ -n $gpgid ]] ; then
-			ZFS "$srchost" send $send_opts --raw -R -i "$last" "$cur" \
+			ZFS "$srchost" send "$send_opts" --raw -R -i "$last" "$cur" \
 				| gpg --trust-model always --encrypt --recipient "$gpgid" \
 				| ssh "$desthost" zfswrite "${tag}_$date.zfssnap.gpg" \
 				|| die $? "zfs incremental send failed"
 			ssh "$desthost" zfslast "$snap"
 		else
-			ZFS "$srchost" send $send_opts --raw -R -i "$last" "$cur" \
+			ZFS "$srchost" send "$send_opts" --raw -R -i "$last" "$cur" \
 				| ssh "$desthost" zfswrite "${tag}_$date.zfssnap" \
 				|| die $? "zfs incremental send failed"
 			ssh "$desthost" zfslast "$snap"
@@ -186,14 +183,13 @@ elif $fromssh ; then
 	# make sure dest exists
 	if [[ $dest =~ : ]] ; then
 		die 1 "$dest must be a local zfs filesystem 💩"
-	elif [[ $(ZFS "" list -H -o name "$dest" 2>/dev/null) != $dest ]] ; then
+	elif [[ $(ZFS "" list -H -o name "$dest" 2>/dev/null) != "$dest" ]] ; then
 		die 1 "$dest must be a local zfs filesystem 💩"
 	fi
 
 	# split src into components
 	if [[ $src =~ : ]] ; then
 		srchost="${src%:*}"
-		srcpath="${src#*:}"
 	else
 		die 1 "$src must be ssh host:path"
 	fi
@@ -202,14 +198,13 @@ elif $fromssh ; then
 	### receive
 	###
 	log "receiving incremental snapshot from $src to $dest"
-	#ZFS "$srchost" send $send_opts -R -i "$last" "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs incremental send failed"
 	for file in $(ssh "$srchost" zfsfind | sort) ; do
 		log "receiving $file from $srchost"
 		if [[ $file =~ \.gpg$ ]] ; then
-			ssh "$srchost" zfsget "$file" | gpg | ZFS "$desthost" receive $recv_opts -Fue "$dest" \
+			ssh "$srchost" zfsget "$file" | gpg | ZFS "$desthost" receive "$recv_opts" -Fue "$dest" \
 				&& ssh "$srchost" rm "$file"
 		else
-			ssh "$srchost" zfsget "$file" | ZFS "$desthost" receive $recv_opts -Fue "$dest" \
+			ssh "$srchost" zfsget "$file" | ZFS "$desthost" receive "$recv_opts" -Fue "$dest" \
 				&& ssh "$srchost" rm "$file"
 		fi
 	done
@@ -229,7 +224,7 @@ destfs="${dest#*:}"
 srcbase="${srcfs##*/}"
 
 # ensure the destination fs exists before proceeding
-if [[ $(ZFS "$desthost" list -H -o name "$destfs" 2>/dev/null) != $destfs ]] ; then
+if [[ $(ZFS "$desthost" list -H -o name "$destfs" 2>/dev/null) != "$destfs" ]] ; then
 	die 1 "destination fs '$destfs' doesn't exist ☠️"
 fi
 
@@ -242,7 +237,7 @@ ZFS "$srchost" snapshot -r "$cur" || die $? "zfs snapshot failed ☠️"
 ###
 ### get newest snapshot on dest - it must exist on src
 ###
-last="$(ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name $destfs/$srcbase | head -n1 | cut -f2 -d@)"
+last="$(ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name "$destfs"/"$srcbase" | head -n1 | cut -f2 -d@)"
 
 ###
 ### send & receive
@@ -250,21 +245,21 @@ last="$(ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name $destfs/$sr
 # 1st time: send full snapshot
 if [[ -z $last ]] ; then
 	log "sending full recursive snapshot from $src to $dest"
-	ZFS "$srchost" send $send_opts --raw -R "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs full send failed ☠️"
+	ZFS "$srchost" send "$send_opts" --raw -R "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs full send failed ☠️"
 # special case: tagged snapshots exist on dest, but src has rotated through all
-elif ! ZFS "$srchost" list $srcfs@$last &>/dev/null ; then
+elif ! ZFS "$srchost" list "$srcfs"@"$last" &>/dev/null ; then
 	die 1 "no incremental path from from $src to $dest"
 # normal case: send incremental
 else
-	log "sending incremental snapshot from $src to $dest (${last#${tag}_}..${cur#*@${tag}_})"
-	ZFS "$srchost" send $send_opts --raw -R -i "$last" "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs incremental send failed ☠️"
+	log "sending incremental snapshot from $src to $dest (${last#"${tag}"_}..${cur#*@"${tag}"_})"
+	ZFS "$srchost" send "$send_opts" --raw -R -i "$last" "$cur" | ZFS "$desthost" receive "$recv_opts" -Fue "$destfs" || die $? "zfs incremental send failed ☠️"
 fi
 
 ###
 ### clean up old snapshots
 ###
-for snap in $(ZFS "$srchost" list -d 1 -t snapshot -H -S creation -o name $srcfs \
+for snap in $(ZFS "$srchost" list -d 1 -t snapshot -H -S creation -o name "$srcfs" \
 	      | grep -F "@${tag}_" | cut -f2 -d@ | tail -n+$((keep+1)) ) ;
 do
-	ZFS "$srchost" destroy -r $srcfs@$snap
+	ZFS "$srchost" destroy -r "$srcfs"@"$snap"
 done
