add raw option to send encrypted datasets

diff --git a/bin/backup-zfs b/bin/backup-zfs
--- a/bin/backup-zfs
+++ b/bin/backup-zfs
@@ -166,13 +166,13 @@ if $tossh ; then
 		log "sending $([[ -n $gpgid ]] && echo "encrypted ")incremental snapshot from $src to $dest (${last#${tag}_}..${cur#*@${tag}_})"
 		#ZFS "$srchost" send $send_opts -R -i "$last" "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs incremental send failed"
 		if [[ -n $gpgid ]] ; then
-			ZFS "$srchost" send $send_opts -R -i "$last" "$cur" \
+			ZFS "$srchost" send $send_opts --raw -R -i "$last" "$cur" \
 				| gpg --trust-model always --encrypt --recipient "$gpgid" \
 				| ssh "$desthost" zfswrite "${tag}_$date.zfssnap.gpg" \
 				|| die $? "zfs incremental send failed"
 			ssh "$desthost" zfslast "$snap"
 		else
-			ZFS "$srchost" send $send_opts -R -i "$last" "$cur" \
+			ZFS "$srchost" send $send_opts --raw -R -i "$last" "$cur" \
 				| ssh "$desthost" zfswrite "${tag}_$date.zfssnap" \
 				|| die $? "zfs incremental send failed"
 			ssh "$desthost" zfslast "$snap"
@@ -250,14 +250,14 @@ last="$(ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name $destfs/$sr
 # 1st time: send full snapshot
 if [[ -z $last ]] ; then
 	log "sending full recursive snapshot from $src to $dest"
-	ZFS "$srchost" send $send_opts -R "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs full send failed"
+	ZFS "$srchost" send $send_opts --raw -R "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs full send failed"
 # special case: tagged snapshots exist on dest, but src has rotated through all
 elif ! ZFS "$srchost" list $srcfs@$last &>/dev/null ; then
 	die 1 "no incremental path from from $src to $dest"
 # normal case: send incremental
 else
 	log "sending incremental snapshot from $src to $dest (${last#${tag}_}..${cur#*@${tag}_})"
-	ZFS "$srchost" send $send_opts -R -i "$last" "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs incremental send failed"
+	ZFS "$srchost" send $send_opts --raw -R -i "$last" "$cur" | ZFS "$desthost" receive $recv_opts -Fue "$destfs" || die $? "zfs incremental send failed"
 fi
 
 ###
