update

diff --git a/bin/backup-zfs b/bin/backup-zfs
--- a/bin/backup-zfs
+++ b/bin/backup-zfs
@@ -159,7 +159,7 @@ fi
 ### resume token support (before creating new snapshot)
 ###
 resume_token="$(
-	ZFS "$desthost" get -H -o value receive_resume_token "$destfs/$srcbase" 2>/dev/null | tr -d '[:space:]'
+	ZFS "$desthost" get -H -o value receive_resume_token "$destfs" 2>/dev/null | tr -d '[:space:]'
 )"
 
 # Resume-Token prüfen und ggf. löschen
@@ -205,7 +205,7 @@ ZFS "$srchost" snapshot -r "$cur" || die $? "zfs snapshot failed ☠️"
 ### (only snapshots with fitting Tag)
 ###
 last="$(
-	ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name "$destfs/$srcbase" 2>/dev/null \
+	ZFS "$desthost" list -d 1 -t snapshot -H -S creation -o name "$destfs" 2>/dev/null \
 		| grep "@${tag}_" \
 		| head -n1 \
 		| cut -f2 -d@
@@ -215,11 +215,11 @@ last="$(
 ### send & receive
 ###
 ### send & receive
-recv_flags="$recv_opts -F"  # -F force overwrite
+recv_flags="$recv_opts -F"
 
-# test, if Dataset exists and is mmouted  → then set -u -e
-if ZFS "$desthost" list -H "$destfs/$srcbase" &>/dev/null ; then
-    recv_flags="$recv_flags -u -e"
+# Wenn Ziel existiert, unmounted empfangen
+if ZFS "$desthost" list -H "$destfs" &>/dev/null ; then
+	recv_flags="$recv_flags -u"
 fi
 
 # Full Send (no common Snapshot)
@@ -227,11 +227,11 @@ if [[ -z $last ]] ; then
 	log "FULL SEND: $cur"
 
 	# clean target if old snapshots exists
-	if ZFS "$desthost" list -H -o name "$destfs/$srcbase" &>/dev/null ; then
-		log "cleaning up old snapshots on $destfs/$srcbase before full send"
-		ZFS "$desthost" list -H -t snapshot -o name "$destfs/$srcbase" 2>/dev/null | \
-			grep "@${tag}_" | xargs -r ZFS "$desthost" destroy -r || die $? "failed to destroy old snapshots on $destfs/$srcbase ☠️"
+	if ZFS "$desthost" list -H -o name "$destfs" &>/dev/null ; then
+		log "cleaning up old snapshots on $destfs before full send"
+		ZFS "$desthost" list -H -t snapshot -o name "$destfs" 2>/dev/null | grep "@${tag}_" | xargs -r ZFS "$desthost" destroy -r || die $? "failed to destroy old snapshots on $destfs ☠️"
 	fi
+
 
 	ZFS "$srchost" send "$send_opts" --raw -R "$cur" | ZFS "$desthost" receive $recv_flags "$destfs" || die $? "zfs full send failed ☠️"
 	#verify_consistency "$srcfs" "$destfs" "$cur"
