Add pull before push

diff --git a/git/bin/push b/git/bin/push
--- a/git/bin/push
+++ b/git/bin/push
@@ -21,11 +21,23 @@ function get_parent() {
 color_error="$(tput sgr 0 1)$(tput setaf 1)"
 color_reset="$(tput sgr0)"
 
-# TODO DRY this b/w pull and push
 branch=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/') || exit $?
 default_remote="origin"
 remote=$(git config "branch.${branch}.remote" || echo "$default_remote")
 remote_branch=$( (git config "branch.${branch}.merge" || echo "refs/heads/$branch") | cut -d/ -f3- )
+
+# pull with rebase before push
+if [ $(git ls-remote --heads $remote $remote_branch + | wc -l) == "1" ]; then
+  echo "🧲 Pull changes from remote before pushing the changes."
+  pull=$(git pull --rebase $remote $remote_branch)
+fi
+exit_code=$?
+if [ $exit_code != 0 ]; then
+  echo -e "${color_error}⚠️ Ouch, pull failed!${color_reset}\n\n$pull"
+  exit $exit_code
+elif echo $pull | grep "Everything up-to-date" >/dev/null; then
+  echo "✌️  Git says everything is up-to-date!"
+fi
 
 # Push & save output
 if [ -z $* ]; then
